import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '../supabaseClient';
import { generateSubjectID } from '../utils/subjectIdGenerator';
import { PatientSelectionScreen } from '../components/ProtocolBuilder/PatientSelectionScreen';
import { PatientLookupModal } from '../components/ProtocolBuilder/PatientLookupModal';
import { Tab1_PatientInfo } from '../components/ProtocolBuilder/Tab1_PatientInfo';
import { Tab2_Medications } from '../components/ProtocolBuilder/Tab2_Medications';
import { Tab3_ProtocolDetails } from '../components/ProtocolBuilder/Tab3_ProtocolDetails';
import { ClinicalInsightsPanel } from '../components/ProtocolBuilder/ClinicalInsightsPanel';
import { SubmissionSuccessScreen } from '../components/ProtocolBuilder/SubmissionSuccessScreen';
import { InteractionChecker } from '../components/clinical/InteractionChecker';
import { ChevronLeft, Check, AlertCircle, Sparkles } from 'lucide-react';



type WorkflowScreen = 'selection' | 'form' | 'success';

interface ProtocolFormData {
  subject_id: string;
  session_number: number;
  patient_age: string;
  patient_sex: string;
  patient_weight_range: string;
  smoking_status: string;
  prior_experience: string;
  concomitant_medication_ids: number[];
  indication_id: number | null;
  substance_id: number | null;
  dosage_mg: number | null;
  dosage_unit: string;
  route_id: number | null;
  consent_verified: boolean;
}

export const ProtocolBuilder = () => {
  const navigate = useNavigate();
  const [screen, setScreen] = useState<WorkflowScreen>('selection');
  const [showLookupModal, setShowLookupModal] = useState(false);
  const [isPreFilled, setIsPreFilled] = useState(false);
  const [preFillDate, setPreFillDate] = useState<string>('');

  const [formData, setFormData] = useState<ProtocolFormData>({
    subject_id: generateSubjectID(),
    session_number: 1,
    patient_age: '',
    patient_sex: '',
    patient_weight_range: '',
    smoking_status: '',
    prior_experience: '',
    concomitant_medication_ids: [],
    indication_id: null,
    substance_id: null,
    dosage_mg: null,
    dosage_unit: 'mg',
    route_id: null,
    consent_verified: false,
  });

  // --- HANDLERS ---

  const handleNewPatient = () => {
    setFormData({
      ...formData,
      subject_id: generateSubjectID(),
      session_number: 1,
    });
    setScreen('form');
    setIsPreFilled(false);
  };

  const handleExistingPatient = () => {
    setShowLookupModal(true);
  };

  const handleSelectPatient = async (patient: any) => {
    // Fetch last record for this patient
    const { data, error } = await supabase
      .from('log_clinical_records')
      .select('*')
      .eq('subject_id', patient.subject_id)
      .order('session_number', { ascending: false })
      .limit(1)
      .single();

    if (error || !data) {
      console.error('Error fetching patient record:', error);
      return;
    }

    // Pre-fill form with last session data (NO session_date)
    setFormData({
      subject_id: data.subject_id,
      session_number: data.session_number + 1, // Auto-increment
      patient_age: data.patient_age || '',
      patient_sex: data.patient_sex || '',
      patient_weight_range: data.patient_weight_range || '',
      smoking_status: data.smoking_status || '',
      prior_experience: data.prior_experience || '',
      concomitant_medication_ids: data.concomitant_medication_ids || [],
      indication_id: data.indication_id,
      substance_id: data.substance_id,
      dosage_mg: data.dosage_mg,
      dosage_unit: data.dosage_unit || 'mg',
      route_id: data.route_id,
      consent_verified: false, // Reset consent
    });

    setIsPreFilled(true);
    setPreFillDate(data.session_date);
    setShowLookupModal(false);
    setScreen('form');
  };

  const handleFormChange = (field: string, value: any) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  };

  const isFormComplete = (): boolean => {
    return !!(
      formData.patient_age &&
      formData.patient_sex &&
      formData.patient_weight_range &&
      formData.indication_id &&
      formData.substance_id &&
      formData.dosage_mg &&
      formData.route_id &&
      formData.consent_verified
    );
  };

  const getCompletedFieldsCount = (): number => {
    let count = 0;
    if (formData.patient_age) count++;
    if (formData.patient_sex) count++;
    if (formData.patient_weight_range) count++;
    if (formData.indication_id) count++;
    if (formData.substance_id) count++;
    if (formData.dosage_mg) count++;
    if (formData.route_id) count++;
    if (formData.consent_verified) count++;
    return count;
  };

  const handleSubmit = async () => {
    if (!isFormComplete()) {
      // The inline missing-fields panel already guides the user — just scroll up
      window.scrollTo({ top: 0, behavior: 'smooth' });
      return;
    }

    // Insert into database (session_date auto-generated by database)
    const { data, error } = await supabase
      .from('log_clinical_records')
      .insert([
        {
          ...formData,
          session_date: new Date().toISOString().split('T')[0], // Auto-generate today's date
          submitted_at: new Date().toISOString(),
          is_submitted: true,
        },
      ])
      .select()
      .single();

    if (error) {
      console.error('Submission error:', error);
      // Surface error without alert — log is sufficient; UI will remain on form
      return;
    }

    setScreen('success');

    // Auto-navigate back to My Protocols after 3 seconds
    setTimeout(() => {
      navigate('/protocols');
    }, 3000);
  };

  const handleBackToReview = () => {
    setScreen('form');
  };

  const handleTrackAnother = () => {
    setScreen('selection');
    setFormData({
      subject_id: generateSubjectID(),
      session_number: 1,
      patient_age: '',
      patient_sex: '',
      patient_weight_range: '',
      smoking_status: '',
      prior_experience: '',
      concomitant_medication_ids: [],
      indication_id: null,
      substance_id: null,
      dosage_mg: null,
      dosage_unit: 'mg',
      route_id: null,
      consent_verified: false,
    });
    setIsPreFilled(false);
  };

  const handleReturnToDashboard = () => {
    navigate('/');
  };

  // --- RENDER ---

  if (screen === 'selection') {
    return (
      <>
        <PatientSelectionScreen
          onNewPatient={handleNewPatient}
          onExistingPatient={handleExistingPatient}
          onBack={() => navigate('/protocols')}
        />
        <PatientLookupModal
          isOpen={showLookupModal}
          onClose={() => setShowLookupModal(false)}
          onSelectPatient={handleSelectPatient}
        />
      </>
    );
  }

  if (screen === 'success') {
    return (
      <SubmissionSuccessScreen
        subjectId={formData.subject_id}
        sessionNumber={formData.session_number}
        onBackToReview={handleBackToReview}
        onTrackAnother={handleTrackAnother}
        onReturnToDashboard={handleReturnToDashboard}
      />
    );
  }

  // Form Screen - Single Page Layout (70/30 Split)
  const showClinicalInsights = !!(formData.patient_age && formData.patient_sex && formData.indication_id && formData.substance_id);

  return (
    <div className="min-h-screen bg-[#0a1628] p-6">
      <div className="max-w-7xl mx-auto">
        {/* Header with Back Button */}
        <div className="mb-6">
          <button
            onClick={() => navigate('/protocols')}
            className="flex items-center gap-2 text-[#14b8a6] hover:text-[#0d9488] mb-4 transition-colors"
          >
            <ChevronLeft className="w-5 h-5" />
            <span className="font-medium">Back to Protocols</span>
          </button>

          <div className="flex items-center justify-between">
            <h1 className="text-3xl font-bold text-[#f8fafc]">Protocol Builder</h1>
            <div className="flex items-center gap-6">
              {/* Progress Indicator */}
              <div className="flex items-center gap-3">
                <div className="text-right">
                  <p className="text-sm text-[#94a3b8]">Completion</p>
                  <p className="text-sm font-bold text-[#f8fafc]">
                    {Math.round((getCompletedFieldsCount() / 8) * 100)}%
                  </p>
                </div>
                <div className="w-24 h-2 bg-[#1e293b] rounded-full overflow-hidden">
                  <div
                    className="h-full bg-gradient-to-r from-[#14b8a6] to-[#10b981] transition-all duration-300"
                    style={{ width: `${(getCompletedFieldsCount() / 8) * 100}%` }}
                  />
                </div>
              </div>

              <span className="text-sm text-[#94a3b8]">
                Subject ID: <span className="font-mono text-[#14b8a6]">{formData.subject_id}</span>
              </span>
              <span className="text-sm text-[#94a3b8]">
                Session {formData.session_number}
              </span>
            </div>
          </div>
        </div>

        {/* Main Content: 70/30 Split */}
        <div className="grid grid-cols-1 lg:grid-cols-[70%_30%] gap-6">
          {/* Left Column: Form (70%) */}
          <div className="space-y-6">
            {/* Section 1: Patient Information */}
            <div className="bg-[#0a1628]/90 backdrop-blur-sm border-2 border-[#1e293b]/50 rounded-2xl p-8 shadow-2xl shadow-black/20 hover:border-[#14b8a6]/30 transition-all duration-300">
              <div className="flex items-center gap-4 mb-8">
                <div className="w-12 h-12 rounded-full bg-gradient-to-br from-[#14b8a6] to-[#0d9488] flex items-center justify-center shadow-lg shadow-[#14b8a6]/30">
                  <span className="text-xl font-black text-slate-300">1</span>
                </div>
                <h2 className="text-3xl font-black bg-gradient-to-r from-[#f8fafc] to-[#cbd5e1] bg-clip-text text-transparent">
                  Patient Information
                </h2>
              </div>
              <Tab1_PatientInfo
                formData={{
                  patient_age: formData.patient_age,
                  patient_sex: formData.patient_sex,
                  patient_weight_range: formData.patient_weight_range,
                  smoking_status: formData.smoking_status,
                  prior_experience: formData.prior_experience,
                }}
                onChange={handleFormChange}
                isPreFilled={isPreFilled}
                preFillDate={preFillDate}
              />
            </div>

            {/* Section 2: Concomitant Medications */}
            <div className="bg-[#0a1628]/90 backdrop-blur-sm border-2 border-[#1e293b]/50 rounded-2xl p-8 shadow-2xl shadow-black/20 hover:border-[#14b8a6]/30 transition-all duration-300">
              <div className="flex items-center gap-4 mb-8">
                <div className="w-12 h-12 rounded-full bg-gradient-to-br from-[#14b8a6] to-[#0d9488] flex items-center justify-center shadow-lg shadow-[#14b8a6]/30">
                  <span className="text-xl font-black text-slate-300">2</span>
                </div>
                <h2 className="text-3xl font-black bg-gradient-to-r from-[#f8fafc] to-[#cbd5e1] bg-clip-text text-transparent">
                  Concomitant Medications
                </h2>
              </div>
              <Tab2_Medications
                selectedMedications={formData.concomitant_medication_ids}
                onChange={(meds) => handleFormChange('concomitant_medication_ids', meds)}
              />
            </div>

            {/* Section 3: Protocol Details */}
            <div className="bg-[#0a1628]/90 backdrop-blur-sm border-2 border-[#1e293b]/50 rounded-2xl p-8 shadow-2xl shadow-black/20 hover:border-[#14b8a6]/30 transition-all duration-300">
              <div className="flex items-center gap-4 mb-8">
                <div className="w-12 h-12 rounded-full bg-gradient-to-br from-[#14b8a6] to-[#0d9488] flex items-center justify-center shadow-lg shadow-[#14b8a6]/30">
                  <span className="text-xl font-black text-slate-300">3</span>
                </div>
                <h2 className="text-3xl font-black bg-gradient-to-r from-[#f8fafc] to-[#cbd5e1] bg-clip-text text-transparent">
                  Protocol Details
                </h2>
              </div>
              <Tab3_ProtocolDetails
                formData={{
                  indication_id: formData.indication_id,
                  substance_id: formData.substance_id,
                  dosage_mg: formData.dosage_mg,
                  dosage_unit: formData.dosage_unit,
                  route_id: formData.route_id,
                  session_number: formData.session_number,
                  session_date: '', // Removed from UI
                  consent_verified: formData.consent_verified,
                }}
                onChange={handleFormChange}
                patientWeight={formData.patient_weight_range}
              />
            </div>

            {/* Submit Section */}
            <div className="bg-[#0a1628]/90 backdrop-blur-sm border-2 border-[#1e293b]/50 rounded-2xl p-8 shadow-2xl shadow-black/20">
              <div className="flex flex-col items-end gap-4">
                {/* Missing Fields Alert */}
                {!isFormComplete() && (
                  <div className="w-full bg-gradient-to-r from-[#ef4444]/10 to-[#dc2626]/10 border-2 border-[#ef4444]/30 rounded-xl px-6 py-4 flex items-start gap-4 mb-2">
                    <AlertCircle className="w-6 h-6 text-[#ef4444] flex-shrink-0 mt-0.5" />
                    <div>
                      <p className="text-base font-bold text-[#ef4444] mb-2">
                        Missing Required Fields
                      </p>
                      <ul className="text-sm text-[#fca5a5] space-y-1.5">
                        {!formData.patient_age && <li>• Age Range</li>}
                        {!formData.patient_sex && <li>• Biological Sex</li>}
                        {!formData.patient_weight_range && <li>• Weight Range</li>}
                        {!formData.indication_id && <li>• Primary Indication</li>}
                        {!formData.substance_id && <li>• Substance</li>}
                        {!formData.dosage_mg && <li>• Dosage</li>}
                        {!formData.route_id && <li>• Administration Route</li>}
                        {!formData.consent_verified && <li>• Consent Verification</li>}
                      </ul>
                    </div>
                  </div>
                )}

                {/* Submit Button */}
                <button
                  onClick={handleSubmit}
                  disabled={!isFormComplete()}
                  className={`
                    px-10 py-5 rounded-xl font-black text-lg
                    flex items-center gap-3 transition-all duration-300
                    ${isFormComplete()
                      ? 'bg-gradient-to-r from-[#14b8a6] to-[#0d9488] hover:from-[#0d9488] hover:to-[#0a7a6a] text-slate-300 shadow-2xl shadow-[#14b8a6]/40 hover:shadow-[#14b8a6]/60 hover:scale-105 border-2 border-[#14b8a6]/50'
                      : 'bg-[#1e293b] text-[#64748b] cursor-not-allowed border-2 border-[#1e293b]'
                    }
                  `}
                >
                  <Check className="w-6 h-6" />
                  Submit to Registry
                </button>
              </div>
            </div>
          </div>

          {/* Right Column: Clinical Insights (30%) */}
          <div>
            <div className="sticky top-6">
              {showClinicalInsights ? (
                <ClinicalInsightsPanel
                  isVisible={showClinicalInsights}
                  substanceId={formData.substance_id}
                  medicationIds={formData.concomitant_medication_ids}
                  indicationId={formData.indication_id}
                  patientAge={formData.patient_age}
                  patientSex={formData.patient_sex}
                  patientWeight={formData.patient_weight_range}
                  dosageMg={formData.dosage_mg}
                />
              ) : (
                <div className="bg-[#0a1628]/90 backdrop-blur-sm border-2 border-[#1e293b]/50 rounded-2xl p-8 text-center shadow-2xl shadow-black/20">
                  <div className="w-20 h-20 mx-auto mb-6 rounded-full bg-gradient-to-br from-[#14b8a6]/20 to-[#0d9488]/20 border-2 border-[#14b8a6]/30 flex items-center justify-center">
                    <Sparkles className="w-10 h-10 text-[#14b8a6]" />
                  </div>
                  <h3 className="text-xl font-bold text-[#f8fafc] mb-3">
                    Clinical Insights
                  </h3>
                  <p className="text-sm text-[#94a3b8] leading-relaxed">
                    Fill in patient details to see personalized safety insights
                  </p>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ProtocolBuilder;